repos:

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
        args: ["-i", --max-line-length=120]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: ["--ignore=W293,W503,E203,F401,F403", --max-line-length=120]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

#Commit message part:

-   repo: https://github.com/Advestis/advestis_hooks
    rev: c76a07d914664e6a841c41355864ddbdc7c03eca
    hooks:
    -   id: format_check
        stages: [commit-msg]
