on:
  push:
    branches:
      - master

name: master
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pull
        run: git config --global user.email "pcotte@advestis.com" && git config --global user.name "pcotteadvestis" && git config pull.rebase false && git pull

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: eu.gcr.io
          repository: sandbox-281209/nmtf
          tag_with_ref: true
          tag_with_sha: true
